apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:5b5798f8b7708da1d78ce00a3337069c362a63d5
        ports:
        - containerPort: 80
