apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 995673420677.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:c05bbe85c952b054f020a16a6a4084476ff838fb
        ports:
        - containerPort: 80
