apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 281145282112.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:79a99c34037a04e7c660b3f7b8b69f94efac24ef
        ports:
        - containerPort: 80
