apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 995673420677.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:c05bbe85c952b054f020a16a6a4084476ff838fb
        ports:
        - containerPort: 80
