apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:728f54992c26b6ed69cb915cabe5bd825b1bdb15
        ports:
        - containerPort: 80
