apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:9a2a2e779ca84758c6f30e9864028d43864ecb5c
        ports:
        - containerPort: 80
