apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:728f54992c26b6ed69cb915cabe5bd825b1bdb15
        ports:
        - containerPort: 80

