apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:5b5798f8b7708da1d78ce00a3337069c362a63d5
        ports:
        - containerPort: 80
