apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-computers:5b5798f8b7708da1d78ce00a3337069c362a63d5
        ports:
        - containerPort: 80
