apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:76f39d1deaa0c41fa58863178554b24190ccf7b0
        ports:
        - containerPort: 80
