apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-phones:f0cadbb444837cdbda857ec382706c03acf1d4de
        ports:
        - containerPort: 80
