apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:7beb454795ec1a811e7010070eda2f30c6f3dfed
        ports:
        - containerPort: 80
