apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 815856636579.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:5b5798f8b7708da1d78ce00a3337069c362a63d5
        ports:
        - containerPort: 80
